build-binary-buster:
  image: debian:buster
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - ./gopherCap.gz
  script:
    - ./build/ci/build_debian.sh
  after_script:
    - gzip gopherCap
  only:
    - tags

build-binary-ubuntu-2004:
  image: ubuntu:20.04
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - ./gopherCap.gz
  script:
    - ./build/ci/build_debian.sh
  after_script:
    - gzip gopherCap
  only:
    - tags
