name: Test go code

on:
  push:
    branches: [ master, next-* ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install libpcap
      run: sudo apt install -y libpcap-dev --install-suggests

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Check for vulnerabilities
      run: govulncheck ./...
